package exceptionhandling;

public class TryCatchDemo {

	public static void main(String[] args) {
		
	     try  
	        {  
	        int num=10/0;    
	        }  
	            
	        catch(ArithmeticException e)  
	        {  
	            System.out.println(e);  
	        }  
	        System.out.println("rest of the code");  
	    }  
	}

}
